#!/usr/bin/env bash

CACHE="$HOME/.cache/target_ip"

valid_ip() {
    local ip=$1
    local IFS=.

    [[ $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1

    read -r o1 o2 o3 o4 <<< "$ip"

    for octet in $o1 $o2 $o3 $o4; do
        ((octet >= 0 && octet <= 255)) || return 1
    done

    return 0
}

# limpiar target
if [[ -z "$1" ]]; then
    rm -f "$CACHE"
    polybar-msg action "#target.hook.0" >/dev/null 2>&1
    exit 0
fi

# validar target
if valid_ip "$1"; then
    echo "$1" > "$CACHE"
else
    echo "Invalid IP"
    exit 1
fi

polybar-msg action "#target.hook.0" >/dev/null 2>&1
