#!/usr/bin/env bash
set -e

echo "[+] Instalando herramientas VMware..."

sudo pacman -S --needed --noconfirm \
    open-vm-tools \
    xorg-xrandr

echo "[+] Activando vmtools..."

sudo systemctl enable --now vmtoolsd

echo "[+] Detectando pantalla..."

OUTPUT=$(xrandr | grep " connected" | cut -d" " -f1)

echo "[+] Output: $OUTPUT"

BEST_MODE=$(xrandr | grep -A1 "$OUTPUT connected" | grep -oP '^[ ]+\K[0-9]+x[0-9]+' | tail -n 1)

BEST_MODE=${BEST_MODE:-1920x1080}

echo "[+] Aplicando: $BEST_MODE"

xrandr --output "$OUTPUT" --mode "$BEST_MODE" || true

echo "[+] Listo"
